
sudo: required

language: php

services:
  - docker

before_install:
  - docker pull moriorgames/bfai-api
  - docker build -t moriorgames/bfai-api .
  - docker run -td --name bfai_api -p 80:80 -p 443:443 moriorgames/bfai-api

script: docker exec -ti bfai_api bash -c 'php phars/phpunit.phar --testdox'

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=moriorgames/bfai-api
  - export TAG=$COMMIT
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:latest
  - docker push $REPO
