
sudo: required

language: php
php:
  - '7.2'

env:
  global:
  - secure: GKWPjuTCCNensENdm9WdsVBA0thCBQD0QUpeeH02/gsQSS09kGjof1ojEfjwLhPEP695AMzocyflNtVCe4zWG6ztSrra2Q+ZaIK1liViPdVpjA4VveMMlPkm8cq+MgXDRxlF1Dwt28vLGZ8StRD11uTMm341ZFuDeUQ93c8OqaQTNzshw3wd/bICDWxXCp9yWUpsh9c/z8STa1P0UxBvOnFreJy/FsaesQY+pyDXlQAtx4e0xIWvHjrnHcn/alLM3dG1WN4ghBLnoyckRgHXxFVYfZSDqj8U+yNj902hDsGIL42g6zSOxx7SarTAFaxqiuMasLCmaqb93JGiLK0eKkniEiM5tTaJxBT4/yUz5ns0hBu1azTdr/vtcfBFLr4WANlmx0Su3y43cIBIoUWOofkwf2l4CoZoy3AiMMr9/p5UjC0OPBZup5kKcTagWWzbsOPb1n1YDjbHxgY0DXmY3qFw55rpRroJhqw5QlxePkTNFOOcjopCj1Wgw/IY5DbBgbfiDASG+4qOcHHZ8Dw6qTqCWumZg32n2L5K3KIo2CUn9n4nTOlk0+n8xdo7+kG9Y2jmhUiPCQda+xTgQZ77fDEAnnmbxqJE2JjujNwtq2cZIesdHWc3jRLNetm2pT46tihZ9pEd5v26Hx62RbajJstGTcKQHnYRzGSpHS7Ui6Q=
  - secure: gX13Y+L4QLwSnWoeOvGKqnDDzrPZRv2LSzyiKBD3MlyL4+PsCOa3Cy9dgT8cUDPzC5h0tT25wL3oqf99J1kTUgg2P733+gqHC6av/2f2LIPGbt/cq+YFl+UzEFgrnaqhaOTXEBbB8kZlg89XO1nUwhQ5gUDhZuJImaH5g/LRv2f+8svSw9yjjapZNGXP34jElTsO42U7rxdESILEAdnmaEV5QYlqlgUu7CgAab7QyDs1w5v5NwXNynkhn2dElZAsT+Boh+GfLr2ODuhC5tN0ghl/ebdp+TYi275XD+k6TwwNWRXTKVaFHUYe4nDQFLdkvjic2TNf3ZcWUaIer3gyVoPi2uqSjwV0kWnXBDl7tkXRZd0BBWsRiKh/V0X1BaD0oyhtg9OmeEFOmcklkddyUGKuCsxvRvNGeyYjbSfnkgaTfNrk2xBKypV8zNUYfITlk5Z9+Wafu/iXQwR32Gee1vDTtkC+YPjGj5DcUSh0l7lc94uZNGQiozwIlwrwymfClhmLCg7Z47Z/SEHWXGEkWtcJWOIU7J76p8vAokQAt0Vdz5wansOz7k7RlDcs08ApFhhvElYXHPtYRs0CFHzr12cOSTUkWMZQR07vkGGAl5K8sxnEz43jPwhQqBpG77RCGz2dEzbOsYl9GAHdTBhHevebtlFPk2vmrEgVcwTJSXE=
  - COMMIT=${TRAVIS_COMMIT}

services:
  - docker

before_install:
  - docker pull moriorgames/bfai-api
  - docker build -t moriorgames/bfai-api .

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=moriorgames/bfai-api
  - export TAG=$COMMIT
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:latest
  - docker push $REPO
