version: '3'

services:
    api:
      image: moriorgames/bfai-api
      ports:
        - "5200:5200"
      links:
        - redis:redis
      volumes:
        - .:/var/www/html

    battle_server:
      image: moriorgames/socket-server
      ports:
        - "5100:5100"
      links:
        - redis:redis

    redis:
      image: redis
      ports:
        - "6379:6379"
