version: '3'

services:
    api:
      image: moriorgames/bfai-api
      container_name: bfai_api
      ports:
        - "80:80"
        - "443:443"
#      volumes:
#        - .:/var/www/html
      links:
        - redis:redis

    battle_server:
      image: moriorgames/socket-server
      container_name: bfai_socket
      ports:
        - "5100:5100"
#      volumes:
#        - ../bfai-battle-server:/var/www/html
      links:
        - redis:redis

    redis:
      image: redis
      container_name: bfai_redis
      ports:
        - "6379:6379"
