index:
    path: /data
    controller: App\Controller\DataController::index

battle_get:
    path: /battle/{token}
    controller: App\Controller\BattleController::get
    methods: GET
    defaults:
        token: abcde

battle_post:
    path: /battle
    controller: App\Controller\BattleController::post
    methods: POST
