index:
    path: /data
    controller: App\Controller\DataController::index

user_get:
    path: /user/{token}
    controller: App\Controller\UserController::get
    methods: GET
    defaults:
        token: null

battle_get:
    path: /battle/{token}
    controller: App\Controller\BattleController::get
    methods: GET
    defaults:
        token: null

battle_post:
    path: /battle
    controller: App\Controller\BattleController::post
    methods: POST
